apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:aL2k9FCXHBPF/T5rOV6P8PIxwbhc/K6H6pBep9bAri58iLpQt+xAEGD0LeyHuaSeknGe0PG9MfI=,iv:GSrtepJqPOWLm1VBF+sH1/bz9JqVcXVjt6wizLRg1Vw=,tag:8UiKR65BsJ6uXDt+BXZ/jA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    age:
        - recipient: age1dx7redapzrz2969tawhjhtg8n4j8922tywewvzmzp6cd5phate0sjdgkzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMlh3L09oWWFvL1dBbzBj
            c21sMUc5SVZ0c2xnSUNwcUhXTnlWbnJCTFRjClpieHlSbkNwZU5DeGZuOXNGTWlT
            KzJrSy8ySDl1T0J1SUJST0xINzY3R2MKLS0tIGJOU1BDeDc4QkxnN29CSjlwVnI1
            eTR6dFNReGNicEQxczNzYVNSQzdoaU0Ku1l3zzlUe6A/YTRtsfw7+jPAT/HB+Q/G
            EkeJdC+g2V03EseGwMIR5z6SgrUaULL6YHCn5dctWPV/KdHLi3+N+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T21:59:14Z"
    mac: ENC[AES256_GCM,data:SMO99COsQHuh2yjfP0jEqgUYhPwyp5kmO/tVEnXbZRKUXR8igHa6TRFedcqSMwMl0EJRcxCJL5Rm35f8v3ngz37JWKWGydVHdXgIx4TwZVZiYalJvvIllF8w/QSxlDofrANDdqjaPmOAFRjY5TMGWPVuApx15U9fNS+xqFmX2FA=,iv:RaaHz18fM2LuoeJTcVEu2mI9edcrof5WLMPWsqlyy+E=,tag:QnEg7gqPYJ6t6qvJfQQjTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
