apiVersion: v1
kind: Secret
metadata:
    name: wikijs-secret
type: Opaque
stringData:
    DB_PASS: ENC[AES256_GCM,data:MK8aPIzvpAVO8q5JXRG6nA==,iv:QPBn4IOjpcn/XFz8z7LwkECr9ZZHLyipd3K28Vr6xT4=,tag:k8q5Gqv5yCkE8eNqaNHBzw==,type:str]
spec:
    decryption:
        provider: sops
        secretRef:
            name: sops-age
sops:
    age:
        - recipient: age1dx7redapzrz2969tawhjhtg8n4j8922tywewvzmzp6cd5phate0sjdgkzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQ2F1NDBuT0ZUVzQxdzhj
            UVlTNG5CNXk2V1RtY0k0OEJndUdTS3hHMFZnCkYrSnhuMzNxYjJaNGg4d2xOa2Nh
            MWkrekdQS2VDYk56bjFvNTRxNm5MZzgKLS0tIFlIYi92Q0FxQjl1YktKU29FeVRW
            M0l3blF4NGpNYXlTK3IwSDZyWDhWZkUKNb+smFqEwpbI+yFmTXKodNBkBrFbZ/0B
            TcQu+7LSBBHmLTtewMaXRHBxRwr1q0UG5Y2qLL5mn7CYhOeZe7uOsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T19:31:27Z"
    mac: ENC[AES256_GCM,data:3wRWKIHxHksUWaFKaBlw5EVV2oMZoeYCoyiMvg9Py5/sXqOrN7jWHS+xX0uii5e8CUHoTsq99XnzryuHSQnDvLwB42EKibV5rzyDNg5P5/PLJmazLiNvqyeSIyyFFmSMXP13tO58VUw2D8pO/dfMqbDds5XTKt1TqvW1r3cCPFI=,iv:20gcuAJ/Q3rGMRc17zSBKA38nMuYZdnat0NRBSijS7Y=,tag:RF+pkU83RwOKIM/Sp4phfg==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.1
