apiVersion: v1
kind: Secret
metadata:
  name: velero-creds
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=0032427eebd0cd6000000000c
    aws_secret_access_key=K003Yd41Vg06u7pR7bGq5qfDbVyP5TA
