apiVersion: ENC[AES256_GCM,data:ugI=,iv:Fca6xgq0yFtSwDOgWtFEQpIBTc3VRs1P1AzoyFgVouU=,tag:v9cd5Z3OBC93CoP1SidhzQ==,type:str]
kind: ENC[AES256_GCM,data:M8dEbJlP,iv:9nL8M3rbUlGxd850UZD+Rrfg1umRCRgt1NDjxZ1STgo=,tag:BJ/olxz1iiXqEvXmavARyA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BMJVWsEsDKtxf5fJ,iv:O8JvTvYCwvkZU99fxEEfVUxe6j++0eTH2Xgz7u6uEJw=,tag:kqXsWlAc4nMtDzHKgIIj2g==,type:str]
    namespace: ENC[AES256_GCM,data:3Uhwr+pF,iv:TzeK0O0baIa0/rTsEomoe9lv5l5X1ShJzOi/Rss4B1Y=,tag:sQnDIbwHmUP4gIiGcWNGMA==,type:str]
type: ENC[AES256_GCM,data:MZy3TbXZ,iv:qDwzopNO1z7cq53cwioFq0R4mLaPRomR/kOY33WtgBQ=,tag:PK5CmEd4JsxpHbG4M8ZRJg==,type:str]
stringData:
    cloud: ENC[AES256_GCM,data:wNmKcvUNDelz22Mbgw7n5Y1uUgzQziJuD03Rh3CfXhRpwIz2nUyMgUAJTKzj/Y3rqrnBy/2e/6atGVDt/QtHgdGRZAGeMzm2vYGsF1LqWpRhYMtUpTEjesQnPT6/n+2biLiuJEz1gHLwNcZR,iv:ZFEDfpMqqMm9U+p0z98YIDuSvHug5kk2N0qxqjLSAjc=,tag:6QaNLPGpKHTZPAR8QsZQLw==,type:str]
sops:
    age:
        - recipient: age1dx7redapzrz2969tawhjhtg8n4j8922tywewvzmzp6cd5phate0sjdgkzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpY0QxMEpRT0JlT08xNWh3
            cnpSZlhaUGZYOGFkTE1CQkhxcXB0amkranlJCkZjcGY1K2FKMmFSVmV5SGttTmdJ
            bVVvN1JxaTJ3T2llUEs0ZFB5S2lxYW8KLS0tIDIzUFpwV0ZONWhNZFVKYkc1ajVm
            Q0JRRUluYWVTNHVpMitIb2VhdFJYcHcK7j+Mr8LOjotR224mdu6gXm/nHG8bkfv1
            LRCpLb6ZcC+fibenxYY6t3IwIJzW+Hn4zr3UVDbgm2MO+nCt3YzKxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T00:22:07Z"
    mac: ENC[AES256_GCM,data:OkDIbRcgVSs6uYx8DnsBehlfFxKt36XXuBdi2hvRb0e8UNoyPkTs5mE8avdHl8eGu4zWbcrG0xypQd84gNRASz7ctR75lqXuDtzPcOC8DBsoHb2u9E5mg1LSFyuCKk72vJreKpN1HIkypxZm2mCr005eQlHWkBsF8N9zTntAkq4=,iv:sXoaVLvVX2aHAJNNqSOjgBPaVUy1Ir4uXnUkshdV3bk=,tag:MJphIh8n8fmbwq7f4aVoMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
